### ISSUE TITLE
dofmricni lists CAL file as EPI file when #vols is large

### ISSUE THREAD

**Issue by dbirman** [justingardner/gru#1]
We accidentally recorded a CAL file that has like 30+ volumes and dofmricni labels the file as an EPI file instead of a CAL file, and tries to include it in subsequent analysis. This could cause big problems with the motion compensation if it gets that far.

Exam #9675 can be used to recreate this error. I tried to fix it myself, but I don't know where the right place to do it is.

**Comment by dbirman** [comment]
(I see now the motion comp isn't implemented yet, but I guess this can be a forward thinking issue).

**Comment by justingardner** [comment]
Should be fixed
